
spring:
  datasource:
    #数据库连接驱动
    driver-class-name: com.mysql.jdbc.Driver
    #数据库用户名
    username: root
    #数据库密码
    password: root
    #数据库URL
    url: jdbc:mysql:///springboot_jdbc
    #数据库连接池
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
      #表示如果表结构存在，修改  如果不存在，创建表结构
      ddl-auto: update
    #表示在控制台上显示sql语句
    show-sql: true
     #表示jpa支持自动创建表结构的语句
    generate-ddl: true



